### PR TITLE
Adding SQL Like format for aliases

### PR DESCRIPTION
**Pull request by XYunknown**
Resolving https://github.com/kaiyou/freeposte.io/issues/38

Needs review by @kaiyou

### CODE REVIEW

**Comment by kaiyou** [comment]
I will add the Alembic migration script and merge this, thank you!

**Comment by kaiyou** [comment]
After some testing, the union does not enforce ordering. this is not critical for now but I will mention it and leave the issue open until resolved.

**Comment by XYunknown** [comment]
I already know a simply and straightforward fix, will push it tonight. Documentation on this feature is however still missing, so we should keep the issue open

**Comment by kaiyou** [comment]
Have a look at the issue #38, I pushed two related commits.

**Pull request merged**
