### PR TITLE
Added config folder for Postfix

### PR DESCRIPTION
**Pull request by jkarlosb**
Feature #29

### CODE REVIEW

**Comment by jkarlosb** [comment]
First, I created a volume with postfix config folder. Second, Into postifix container start.sh I added a script to verify optional main.cf and if it exist, override the entries through postconf e flag. Next, the script checks if some .map file exist (e.g. transport.map, sasl_passwd.map, etc.), it copies to /etc/postfix folder, executes postmap and configures its perms. Example config files:

/freeposte/config/postfix/main.cf:
```
relayhost = [email-smtp.eu-west-1.amazonaws.com]:25
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd.map
smtp_use_tls = yes
smtp_tls_security_level = encrypt
smtp_tls_note_starttls_offer = yes
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
```

/freeposte/config/postfix/sasl_passwd.map:
```
[email-smtp.eu-west-1.amazonaws.com]:25 USER:PASSWORD
```

**Comment by kaiyou** [comment]
Sounds very good.

Because we have very few configuration files for each service, I am thinking about gathering them all in something like ``/freeposte/overrides`` (or anything that clearly states that these are overrides, not the actual configuration files) and overriding on a filename basis with proper documentation to avoid having too many directories and different mount points.

The documentation could state something like "create a main.cf to override the postfix configuration", and maybe use some more meaningful names like ``postfix.conf``, ``dovecot.conf``, etc.

The only problem I see would be confidentiality between containers for password maps for instance. Does not sound like too much of a risk. What do you think?

**Comment by jkarlosb** [comment]
Ok, It seems perfect for me, to avoid having too many mount points. About the confidentiality between containers I think this isn't a risk for now.

**Comment by kaiyou** [comment]
Sounds perfect. Let's go for master, I will test it tonight. Thanks!

**Pull request merged**
